blueprint:
  name: "IKEA Bilresa – Scrollwheel"
  description: "Eine Automation für beide Dreh-Richtungen mit unterschiedlichen multi_press_8 Aktionen"
  domain: automation
  input:
    event_right:
      name: "Event Entity – Drehen Rechts"
      selector:
        entity:
          domain: event
    
    event_left:
      name: "Event Entity – Drehen Links"
      selector:
        entity:
          domain: event
    
    target_light:
      name: "Ziellampe"
      selector:
        entity:
          domain: light
    
    brightness_per_step:
      name: "Helligkeit pro Schritt (%)"
      default: 5
      selector:
        number:
          min: 1
          max: 20
          unit_of_measurement: "%"
    
    multi_press_8_right:
      name: "multi_press_8 Aktion – Rechts"
      description: "Was passiert bei 8× Drehen RECHTS?"
      selector:
        select:
          options:
            - label: "Lampe ausschalten"
              value: "toggle_off"
            - label: "Maximale Helligkeit (100%)"
              value: "max_brightness"
            - label: "Minimale Helligkeit (10%)"
              value: "min_brightness"
      default: "toggle_off"
    
    multi_press_8_left:
      name: "multi_press_8 Aktion – Links"
      description: "Was passiert bei 8× Drehen LINKS?"
      selector:
        select:
          options:
            - label: "Lampe ausschalten"
              value: "toggle_off"
            - label: "Maximale Helligkeit (100%)"
              value: "max_brightness"
            - label: "Minimale Helligkeit (10%)"
              value: "min_brightness"
      default: "toggle_off"

trigger:
  - platform: state
    entity_id: 
      - !input event_right
      - !input event_left
    attribute: event_type

action:
  - variables:
      brightness_step_value: !input brightness_per_step
      multi_press_8_right_value: !input multi_press_8_right
      multi_press_8_left_value: !input multi_press_8_left
      target_light_entity: !input target_light
      event_right_value: !input event_right
      event_left_value: !input event_left
      
      press_count: "{{ state_attr(trigger.entity_id, 'event_type') | regex_replace('^multi_press_(\\d+)$', '\\1') | int(1) }}"
      is_right: "{{ trigger.entity_id == event_right_value }}"
      direction_multiplier: "{{ 1 if is_right else -1 }}"
      brightness_delta: "{{ (brightness_step_value | int(5) * press_count * direction_multiplier) }}"
      light_is_on: "{{ states(target_light_entity) == 'on' }}"
      multi_press_8_action: "{{ multi_press_8_right_value if is_right else multi_press_8_left_value }}"

  - if:
      - condition: template
        value_template: "{{ light_is_on }}"
    then:
      - if:
          - condition: template
            value_template: "{{ press_count < 8 }}"
        then:
          - service: light.turn_on
            target:
              entity_id: "{{ target_light_entity }}"
            data:
              brightness_step_pct: "{{ brightness_delta }}"
        else:
          - choose:
              - conditions:
                  - condition: template
                    value_template: "{{ multi_press_8_action == 'toggle_off' }}"
                sequence:
                  - service: light.turn_off
                    target:
                      entity_id: "{{ target_light_entity }}"

              - conditions:
                  - condition: template
                    value_template: "{{ multi_press_8_action == 'max_brightness' }}"
                sequence:
                  - service: light.turn_on
                    target:
                      entity_id: "{{ target_light_entity }}"
                    data:
                      brightness_pct: 100

              - conditions:
                  - condition: template
                    value_template: "{{ multi_press_8_action == 'min_brightness' }}"
                sequence:
                  - service: light.turn_on
                    target:
                      entity_id: "{{ target_light_entity }}"
                    data:
                      brightness_pct: 10
    else:
      - if:
          - condition: template
            value_template: "{{ direction_multiplier > 0 and press_count < 8 }}"
        then:
          - service: light.turn_on
            target:
              entity_id: "{{ target_light_entity }}"
            data:
              brightness_pct: "{{ brightness_delta | int | max(10) | min(100) }}"

mode: restart
