blueprint:
  name: "IKEA Bilresa Scroll Wheel – Universal Smart Fix"
  description: "Matter-based control. Automatically detects if target is a light (with safety lock) or a numeric entity."
  domain: automation
  input:
    # --- Entities ---
    scroll_right_event:
      name: "Scroll Wheel Event – Right" 
      selector:
        entity:
          domain: event
    scroll_left_event:
      name: "Scroll Wheel Event – Left"
    selector:
        entity:
          domain: event
    center_button_event:
      name: "Center Button Event"
      selector:
        entity:
          domain: event
    
    target_entity:
      name: "Target Scroll Entity"
      description: "Select a Light, Number or Input Number."
      selector:
        entity:
          filter: 
            domain:
              - light
              - number
              - input_number

    # --- Settings ---
    lock_when_off:
      name: "Lock when off (Lights only)"
      description: "Prevents rotation from turning on the light if it's currently off."
      default: true
      selector:
        boolean: {}
    min_value:
      name: "Minimum Brightness (Lights only)"
      description: "Light will not go below this % when scrolling down."
      default: 10
      selector:
        number:
          min: 0
          max: 100
          unit_of_measurement: "%"
    step_size:
      name: "Step Size"
      default: 5
      selector:
        number:
          min: 1
          max: 20

    # --- Actions ---
    action_single:
      name: "Single Press"
      default: []
      selector:
        action: {}
    action_double:
      name: "Double Press"
      default: []
      selector:
        action: {}
    action_triple:
      name: "Triple Press"
      default: []
      selector:
        action: {}
    action_hold:
      name: "Hold"
      default: []
      selector:
        action: {}

trigger:
  - platform: state
    entity_id: !input scroll_right_event
    id: "right"
  - platform: state
    entity_id: !input scroll_left_event
    id: "left"
  - platform: state
    entity_id: !input center_button_event
    id: "center"

action:
  - variables:
      target: !input target_entity
      lock_active: !input lock_when_off
      min_val: !input min_value
      step: !input step_size
      
      domain: "{{ target.split('.')[0] }}"
      is_light: "{{ domain == 'light' }}"
      
      current_val: >
        {% if is_light %}
          {{ (state_attr(target, 'brightness') | int(0) / 255 * 100) | round(0) | int }}
        {% else %}
          {{ states(target) | float(0) | int }}
        {% endif %}
      
      is_on: "{{ states(target) == 'on' }}"
      event_type: "{{ state_attr(trigger.entity_id, 'event_type') }}"
      press_count: "{{ trigger.to_state.attributes.totalNumberOfPressesCounted | int(1) }}"

  - choose:
      # --- RECHTS DREHEN (Erhöhen) ---
      - conditions:
          - condition: template
            value_template: "{{ trigger.id == 'right' }}"
          - condition: template
            value_template: "{{ not is_light or (is_on or not lock_active) }}"
        sequence:
          - choose:
              - conditions: "{{ is_light }}"
                sequence:
                  - service: light.turn_on
                    target:
                      entity_id: !input target_entity
                    data:
                      brightness_pct: "{{ [ (current_val + (step * press_count)) | int, 100 ] | min }}"
              - conditions: "{{ not is_light }}"
                sequence:
                  - service: "{{ domain }}.set_value"
                    target:
                      entity_id: !input target_entity
                    data:
                      value: "{{ current_val + (step * press_count) }}"

      # --- LINKS DREHEN (Verringern) ---
      - conditions:
          - condition: template
            value_template: "{{ trigger.id == 'left' }}"
          - condition: template
            # Nur ausführen, wenn Lampe an ist (oder es kein Licht ist)
            value_template: "{{ not is_light or is_on }}"
        sequence:
          - choose:
              - conditions: "{{ is_light }}"
                sequence:
                  # Verhindert Befehle, wenn wir schon am Limit sind
                  - condition: template
                    value_template: "{{ current_val > min_val }}"
                  - service: light.turn_on
                    target:
                      entity_id: !input target_entity
                    data:
                      # Wir nehmen den berechneten Wert, aber er darf NIEMALS kleiner als min_val sein.
                      # Mindestens 1%, damit die Lampe nicht ausgeht.
                      brightness_pct: >
                        {% set next_val = (current_val - (step * press_count)) | int %}
                        {{ [next_val, min_val | int, 1] | max }}
              - conditions: "{{ not is_light }}"
                sequence:
                  - service: "{{ domain }}.set_value"
                    target:
                      entity_id: !input target_entity
                    data:
                      value: "{{ current_val - (step * press_count) }}"

      # --- CENTER BUTTON ---
      - conditions: "{{ trigger.id == 'center' and (event_type == 'short_release' or event_type == 'multi_press_1') }}"
        sequence: !input action_single
      - conditions: "{{ trigger.id == 'center' and (event_type == 'multi_press_2' or press_count == 2) }}"
        sequence: !input action_double
      - conditions: "{{ trigger.id == 'center' and (event_type == 'multi_press_3' or press_count == 3) }}"
        sequence: !input action_triple
      - conditions: "{{ trigger.id == 'center' and event_type == 'long_press' }}"
        sequence: !input action_hold

mode: queued
max: 20
