blueprint:
  name: "IKEA Bilresa Scroll Wheel – Rework"
  description: "Matter-based control with power-on lock, minimum brightness, and multi-press center button."
  domain: automation
  input:
    scroll_right_event:
      name: "Scroll Wheel Event – Right"
      selector:
        entity:
          domain: event
    scroll_left_event:
      name: "Scroll Wheel Event – Left"
      selector:
        entity:
          domain: event
    center_button_event:
      name: "Center Button Event"
      selector:
        entity:
          domain: event
    target_light:
      name: "Target Light"
      selector:
        entity:
          domain: light
    lock_when_off:
      name: "Lock when off"
      description: "Prevents turning on the light by rotating it when it is currently off."
      default: true
      selector:
        boolean: {}
    min_brightness:
      name: "Minimum Brightness (%)"
      description: "The light will not go below this value when scrolling down."
      default: 10
      selector:
        number:
          min: 1
          max: 20
          unit_of_measurement: "%"
    action_single:
      name: "Single Press"
      default: []
      selector:
        action: {}
    action_double:
      name: "Double Press"
      default: []
      selector:
        action: {}
    action_triple:
      name: "Triple Press"
      default: []
      selector:
        action: {}
    action_hold:
      name: "Hold"
      default: []
      selector:
        action: {}

trigger:
  - platform: state
    entity_id: !input scroll_right_event
    id: "right"
  - platform: state
    entity_id: !input scroll_left_event
    id: "left"
  - platform: state
    entity_id: !input center_button_event
    id: "center"

action:
  - variables:
      target_entity: !input target_light
      btn_event_ent: !input center_button_event
      lock_active: !input lock_when_off
      min_bright: !input min_brightness
      is_on: "{{ states(target_entity) == 'on' }}"
      current_pct: "{{ (state_attr(target_entity, 'brightness') | int(0) / 255 * 100) | round(0) }}"
      event_type: "{{ state_attr(trigger.entity_id, 'event_type') }}"
      press_count: "{{ trigger.to_state.attributes.totalNumberOfPressesCounted | int(1) }}"

  - choose:
      - conditions:
          - condition: template
            value_template: "{{ trigger.id == 'right' }}"
          - condition: template
            value_template: "{{ is_on or not lock_active }}"
        sequence:
          - service: light.turn_on
            target:
              entity_id: !input target_light
            data:
              brightness_step_pct: "{{ 5 * press_count }}"

      - conditions:
          - condition: template
            value_template: "{{ trigger.id == 'left' and is_on }}"
          - condition: template
            value_template: "{{ current_pct > min_bright }}"
        sequence:
          - service: light.turn_on
            target:
              entity_id: !input target_light
            data:
              brightness_step_pct: "{{ -5 * press_count }}"

      - conditions:
          - condition: template
            value_template: "{{ trigger.entity_id == btn_event_ent and (event_type == 'short_release' or event_type == 'multi_press_1') }}"
        sequence: !input action_single

      - conditions:
          - condition: template
            value_template: "{{ trigger.entity_id == btn_event_ent and (event_type == 'multi_press_2' or press_count == 2) }}"
        sequence: !input action_double

      - conditions:
          - condition: template
            value_template: "{{ trigger.entity_id == btn_event_ent and (event_type == 'multi_press_3' or press_count == 3) }}"
        sequence: !input action_triple

      - conditions:
          - condition: template
            value_template: "{{ trigger.entity_id == btn_event_ent and event_type == 'long_press' }}"
        sequence: !input action_hold

mode: queued
max: 20
