blueprint:
  name: "IKEA Bilresa Scroll Wheel – Rework"
  description: "Matter-basierte Steuerung mit Einschalt-Lock, Minimum-Brightness und Multi-Press Center Button."
  domain: automation
  input:
    # Entities
    scroll_right_event:
      name: "Scroll Wheel Event – Rechts"
      selector:
        entity:
          domain: event
    scroll_left_event:
      name: "Scroll Wheel Event – Links"
      selector:
        entity:
          domain: event
    center_button_event:
      name: "Center Button Event"
      selector:
        entity:
          domain: event
    target_light:
      name: "Ziellampe"
      selector:
        entity:
          domain: light

    # Settings
    lock_when_off:
      name: "Lock wenn Aus"
      description: "Verhindert das Einschalten durch Drehen, wenn die Lampe aus ist."
      default: true
      selector:
        boolean: {}
    min_brightness:
      name: "Minimale Helligkeit (%)"
      description: "Die Lampe wird beim Runterdrehen nicht dunkler als dieser Wert."
      default: 10
      selector:
        number:
          min: 1
          max: 20
          unit_of_measurement: "%"
    
    # Actions for Center Button
    action_single:
      name: "1x Drücken"
      default: []
      selector:
        action: {}
    action_double:
      name: "2x Drücken"
      default: []
      selector:
        action: {}
    action_triple:
      name: "3x Drücken"
      default: []
      selector:
        action: {}
    action_hold:
      name: "Halten"
      default: []
      selector:
        action: {}

trigger:
  - platform: state
    entity_id: !input scroll_right_event
    id: "right"
  - platform: state
    entity_id: !input scroll_left_event
    id: "left"
  - platform: state
    entity_id: !input center_button_event
    id: "center"

action:
  - variables:
      # Inputs zu Variablen für Templates
      target_entity: !input target_light
      btn_event_ent: !input center_button_event
      lock_active: !input lock_when_off
      min_bright: !input min_brightness
      
      # Status-Abfrage
      is_on: "{{ states(target_entity) == 'on' }}"
      current_pct: "{{ (state_attr(target_entity, 'brightness') | int(0) / 255 * 100) | round(0) }}"
      
      # Event Daten
      event_type: "{{ state_attr(trigger.entity_id, 'event_type') }}"
      press_count: "{{ trigger.to_state.attributes.totalNumberOfPressesCounted | int(1) }}"

  - choose:
      # --- SCROLL LOGIK (RECHTS) ---
      - conditions:
          - condition: template
            value_template: "{{ trigger.id == 'right' }}"
          - condition: template
            # Lock Prüfung: Nur ausführen wenn an ODER Lock deaktiviert
            value_template: "{{ is_on or not lock_active }}"
        sequence:
          - service: light.turn_on
            target:
              entity_id: !input target_light
            data:
              brightness_step_pct: "{{ 5 * press_count }}"

      # --- SCROLL LOGIK (LINKS) ---
      - conditions:
          - condition: template
            value_template: "{{ trigger.id == 'left' and is_on }}"
          - condition: template
            # Stoppt bei Erreichen der Min-Brightness
            value_template: "{{ current_pct > min_bright }}"
        sequence:
          - service: light.turn_on
            target:
              entity_id: !input target_light
            data:
              brightness_step_pct: "{{ -5 * press_count }}"

      # --- CENTER BUTTON LOGIK (DEINE SYNTAX) ---
      
      # 1x Press
      - conditions:
          - condition: template
            value_template: "{{ trigger.entity_id == btn_event_ent and (event_type == 'short_release' or event_type == 'multi_press_1') }}"
        sequence: !input action_single

      # 2x Press
      - conditions:
          - condition: template
            value_template: "{{ trigger.entity_id == btn_event_ent and (event_type == 'multi_press_2' or press_count == 2) }}"
        sequence: !input action_double

      # 3x Press
      - conditions:
          - condition: template
            value_template: "{{ trigger.entity_id == btn_event_ent and (event_type == 'multi_press_3' or press_count == 3) }}"
        sequence: !input action_triple

      # Hold
      - conditions:
          - condition: template
            value_template: "{{ trigger.entity_id == btn_event_ent and event_type == 'long_press' }}"
        sequence: !input action_hold

mode: queued
max: 20
