blueprint:
  name: "IKEA Bilresa Scroll Wheel – Universal"
  description: "Control lights or any numeric value (number/input_number) with a power-on lock and multi-press button."
  domain: automation
  input:
    # --- Mode Switch ---
    control_mode:
      name: "Control Mode"
      description: "Choose if you want to control a light or a generic numeric entity."
      default: "light"
      selector:
        select:
          options:
            - label: "Light (Brightness %)"
              value: "light"
            - label: "Generic Numeric (number / input_number)"
              value: "numeric"

    # --- Entities ---
    scroll_right_event:
      name: "Scroll Wheel Event – Right"
      selector:
        entity:
          domain: event
    scroll_left_event:
      name: "Scroll Wheel Event – Left"
      selector:
        entity:
          domain: event
    center_button_event:
      name: "Center Button Event"
      selector:
        entity:
          domain: event
    
    target_entity:
      name: "Target Entity"
      description: "The Light OR the numeric entity to control."
      selector:
        entity:
          filter: 
            domain:
              - light
              - number
            
    # --- Settings ---
    lock_when_off:
      name: "Lock when off / at minimum"
      description: "Light: Prevents turning on if off. Numeric: Prevents increasing if at 0/min."
      default: true
      selector:
        boolean: {}
    min_value:
      name: "Minimum Value (%)"
      description: "The entity will not go below this value when scrolling down."
      default: 10
      selector:
        number:
          min: 0
          max: 100
          unit_of_measurement: "%"
    step_size:
      name: "Step Size"
      description: "Value change per tick (multiplied by rotation speed)."
      default: 5
      selector:
        number:
          min: 1
          max: 20

    # --- Actions ---
    action_single:
      name: "Single Press"
      default: []
      selector:
        action: {}
    action_double:
      name: "Double Press"
      default: []
      selector:
        action: {}
    action_triple:
      name: "Triple Press"
      default: []
      selector:
        action: {}
    action_hold:
      name: "Hold"
      default: []
      selector:
        action: {}

trigger:
  - platform: state
    entity_id: !input scroll_right_event
    id: "right"
  - platform: state
    entity_id: !input scroll_left_event
    id: "left"
  - platform: state
    entity_id: !input center_button_event
    id: "center"

action:
  - variables:
      mode: !input control_mode
      target: !input target_entity
      lock_active: !input lock_when_off
      min_val: !input min_value
      step: !input step_size
      
      # Status calculations
      is_light: "{{ mode == 'light' }}"
      current_val: >
        {% if is_light %}
          {{ (state_attr(target, 'brightness') | int(0) / 255 * 100) | round(0) }}
        {% else %}
          {{ states(target) | float(0) }}
        {% endif %}
      
      is_active: >
        {% if is_light %}
          {{ states(target) == 'on' }}
        {% else %}
          {{ states(target) | float(0) > 0 }}
        {% endif %}

      event_type: "{{ state_attr(trigger.entity_id, 'event_type') }}"
      press_count: "{{ trigger.to_state.attributes.totalNumberOfPressesCounted | int(1) }}"

  - choose:
      # --- SCROLL RIGHT (UP) ---
      - conditions:
          - condition: template
            value_template: "{{ trigger.id == 'right' }}"
          - condition: template
            value_template: "{{ is_active or not lock_active }}"
        sequence:
          - choose:
              - conditions: "{{ is_light }}"
                sequence:
                  - service: light.turn_on
                    target:
                      entity_id: !input target_entity
                    data:
                      brightness_step_pct: "{{ step * press_count }}"
              - conditions: "{{ not is_light }}"
                sequence:
                  - service: >
                      {% if target.split('.')[0] == 'input_number' %} input_number.set_value 
                      {% else %} number.set_value {% endif %}
                    target:
                      entity_id: !input target_entity
                    data:
                      value: "{{ [current_val + (step * press_count), 100] | min }}"

      # --- SCROLL LEFT (DOWN) ---
      - conditions:
          - condition: template
            value_template: "{{ trigger.id == 'left' and is_active }}"
          - condition: template
            value_template: "{{ current_val > min_val }}"
        sequence:
          - choose:
              - conditions: "{{ is_light }}"
                sequence:
                  - service: light.turn_on
                    target:
                      entity_id: !input target_entity
                    data:
                      brightness_step_pct: "{{ -step * press_count }}"
              - conditions: "{{ not is_light }}"
                sequence:
                  - service: >
                      {% if target.split('.')[0] == 'input_number' %} input_number.set_value 
                      {% else %} number.set_value {% endif %}
                    target:
                      entity_id: !input target_entity
                    data:
                      value: "{{ [current_val - (step * press_count), min_val] | max }}"

      # --- CENTER BUTTON ---
      - conditions:
          - condition: template
            value_template: "{{ trigger.id == 'center' and (event_type == 'short_release' or event_type == 'multi_press_1') }}"
        sequence: !input action_single

      - conditions:
          - condition: template
            value_template: "{{ trigger.id == 'center' and (event_type == 'multi_press_2' or press_count == 2) }}"
        sequence: !input action_double

      - conditions:
          - condition: template
            value_template: "{{ trigger.id == 'center' and (event_type == 'multi_press_3' or press_count == 3) }}"
        sequence: !input action_triple

      - conditions:
          - condition: template
            value_template: "{{ trigger.id == 'center' and event_type == 'long_press' }}"
        sequence: !input action_hold

mode: queued
max: 20
