blueprint:
  name: "IKEA Bilresa Scroll Wheel – One Layer (Matter/Universal)"
  description: >
    Advanced Matter-optimized controller for the IKEA Bilresa Scroll Wheel. 
    Note: This blueprint handles ONE layer. If you want to use all 3 remote layers, create separate automations for each layer using their respective event entities.
  domain: automation
  input:
    # --- Entities ---
    scroll_right_event:
      name: "Scroll Wheel Event – Clockwise"
      description: "Increase Value. Usually Button 1, 4, or 7 (Layer 1, 2, or 3)."
      selector:
        entity:
          domain: event
    scroll_left_event:
      name: "Scroll Wheel Event – Counterclockwise"
      description: "Decrease Value. Usually Button 2, 5, or 8 (Layer 1, 2, or 3)."
      selector:
        entity:
          domain: event
    center_button_event:
      name: "Center Button Event"
      description: "Usually Button 3, 6, or 9 (Layer 1, 2, or 3)."
      selector:
        entity:
          domain: event

    target_entity:
      name: "Target Entity"
      description: "The Light, Number, or Input Number to control."
      selector:
        entity:
          filter:
            domain:
              - light
              - number
              - input_number
              - media_player

    # --- Settings ---
    lock_when_off:
      name: "Lock when off (Lights only)"
      description: "Prevents rotation from turning on the light if it is currently off."
      default: true
      selector:
        boolean: {}
    min_value:
      name: "Minimum Brightness (Lights only)"
      description: "The light will not go below this % when scrolling down."
      default: 10
      selector:
        number:
          min: 0
          max: 100
          unit_of_measurement: "%"
    step_size:
      name: "Step Size"
      description: "Percentage change per scroll tick."
      default: 5
      selector:
        number:
          min: 1
          max: 20

    # --- Actions for Center Button ---
    action_single:
      name: "Single Press"
      default: []
      selector:
        action: {}
    action_double:
      name: "Double Press"
      default: []
      selector:
        action: {}
    action_triple:
      name: "Triple Press"
      default: []
      selector:
        action: {}
    action_hold:
      name: "Hold"
      default: []
      selector:
        action: {}

trigger:
  - platform: state
    entity_id: !input scroll_right_event
    id: "right"
  - platform: state
    entity_id: !input scroll_left_event
    id: "left"
  - platform: state
    entity_id: !input center_button_event
    id: "center"

action:
  - variables:
      target_ent: !input target_entity
      lock_act: !input lock_when_off
      min_v: !input min_value
      step_v: !input step_size
      
      domain: "{{ target_ent.split('.')[0] }}"
      is_light: "{{ domain == 'light' }}"
      
      # Calculate current value with precision rounding
      current_val: >
        {% if is_light %}
          {{ (state_attr(target_ent, 'brightness') | int(0) / 2.55) | round(0) | int }}
        {% else %}
          {{ states(target_ent) | float(0) | round(0) | int }}
        {% endif %}
      
      is_on: "{{ states(target_ent) == 'on' }}"
      # Context-safe trigger attributes
      press_count: "{{ trigger.to_state.attributes.totalNumberOfPressesCounted | int(1) if trigger is defined and trigger.to_state is defined else 1 }}"
      event_type: "{{ state_attr(trigger.entity_id, 'event_type') if trigger is defined else 'none' }}"

  - choose:
      # --- SCROLL RIGHT ---
      - conditions:
          - condition: template
            value_template: "{{ trigger.id == 'right' }}"
          - condition: template
            value_template: "{{ not is_light or (is_on or not lock_act) }}"
        sequence:
          - choose:
              - conditions: "{{ is_light }}"
                sequence:
                  - service: light.turn_on
                    target:
                      entity_id: !input target_entity
                    data:
                      brightness_pct: "{{ [ (current_val + (step_v * press_count)) | int, 100 ] | min }}"
              - conditions: "{{ not is_light }}"
                sequence:
                  - service: "{{ domain }}.set_value"
                    target:
                      entity_id: !input target_entity
                    data:
                      value: "{{ [ (current_val + (step_v * press_count)) | int, 100 ] | min }}"

      # --- SCROLL LEFT ---
      - conditions:
          - condition: template
            value_template: "{{ trigger.id == 'left' }}"
          - condition: template
            value_template: "{{ not is_light or is_on }}"
        sequence:
          - choose:
              - conditions: "{{ is_light }}"
                sequence:
                  - service: light.turn_on
                    target:
                      entity_id: !input target_entity
                    data:
                      brightness_pct: >
                        {% set calc = (current_val - (step_v * press_count)) | int %}
                        {% set minimum = min_v | int %}
                        {{ [calc, minimum, 0] | max }}
              - conditions: "{{ not is_light }}"
                sequence:
                  - service: "{{ domain }}.set_value"
                    target:
                      entity_id: !input target_entity
                    data:
                      value: >
                        {% set calc = (current_val - (step_v * press_count)) | int %}
                        {{ [calc, 0] | max }}

      # --- CENTER BUTTON ---
      - conditions: "{{ trigger.id == 'center' and (event_type == 'short_release' or event_type == 'multi_press_1') }}"
        sequence: !input action_single
      - conditions: "{{ trigger.id == 'center' and (event_type == 'multi_press_2' or press_count == 2) }}"
        sequence: !input action_double
      - conditions: "{{ trigger.id == 'center' and (event_type == 'multi_press_3' or press_count == 3) }}"
        sequence: !input action_triple
      - conditions: "{{ trigger.id == 'center' and event_type == 'long_press' }}"
        sequence: !input action_hold

mode: queued
max: 20
